package net.ecoporium.spartan.model.violation

enum class Violation(val fancyName: String) {

    EXPLOITS("Exploits"),
    ENTITY_MOVE("EntityMove"),
    NO_SWING("NoSwing"),
    IRREGULAR_MOVEMENTS("IrregularMovements"),
    CLIP("Clip"),
    IMPOSSIBLE_ACTIONS("ImpossibleActions"),
    ITEM_DROPS("ItemDrops"),
    AUTO_RESPAWN("AutoRespawn"),
    INVENTORY_CLICKS("InventoryClicks"),
    SPRINT("Sprint"),
    JESUS("Jesus"),
    NO_SLOWDOWN("NoSlowdown"),
    CRITICALS("Criticals"),
    GHOST_HAND("GhostHand"),
    BLOCK_REACH("BlockReach"),
    ELYTRA_MOVE("ElytraMove"),
    FAST_BOW("FastBow"),
    FAST_CLICKS("FastClicks"),
    FAST_HEAL("FastHeal"),
    IMPOSSIBLE_INVENTORY("ImpossibleInventory"),
    HIT_REACH("HitReach"),
    FAST_BREAK("FastBreak"),
    SPEED("Speed"),
    FAST_PLACE("FastPlace"),
    MORE_PACKETS("MorePackets"),
    NO_FALL("NoFall"),
    FAST_EAT("FastEat"),
    VELOCITY("Velocity"),
    KILL_AURA("KillAura"),
    FOUND_COAL("Found Coal"),
    FOUND_COPPER("Found Copper"),
    FOUND_IRON("Found Iron"),
    FOUND_LAPIS("Found Lapis"),
    FOUND_REDSTONE("Found Redstone"),
    FOUND_GOLD("Found Gold"),
    FOUND_EMERALD("Found Emerald"),
    FOUND_DIAMOND("Found Diamond"),
    FOUND_NETHER_QUARTZ("Found Nether Quartz"),
    FOUND_ANCIENT_DEBRIS("Found Ancient Debris")

}