name: SpartanWebhooks
version: 2.0
authors: [ bobby29831 ]
api-version: 1.18
depend: [ Spartan ]
description: Adds webhook support to the popular Minecraft Anti-Cheat called Spartan
main: net.ecoporium.spartan.SpartanWebhooks